Added deprecation notice to master README.md
twilio/video-quickstart-objc pull request #142
Opened 2019-06-13 19:45 UTC by paynerc

Added a deprecation notice and link to the video-quickstart-ios repository.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

2019-06-13 19:48 UTC, ceaglest requested changes

2019-06-13 19:48 UTC, ceaglest commented on README.md
> +> This repository has been deprecated and shall no longer be maintained. All Objective-C examples have been merged into the [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios) repo
"continued" -> "continue" 

Suggestion: "shall" -> "will"

2019-06-13 19:49 UTC, paynerc commented on README.md
> +> This repository has been deprecated and shall no longer be maintained. All Objective-C examples have been merged into the [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios) repo
> This repository has been deprecated and will no longer be maintained. All Objective-C examples have been merged into the [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios) repository and will continue to be maintained there.

2019-06-13 19:52 UTC, ceaglest approved these changes

2019-06-14 21:24 UTC, piyushtank approved these changes

2019-06-14 21:25 UTC, piyushtank approved these changes

2019-06-14 21:26 UTC, piyushtank approved these changes

2019-06-14 23:52 UTC, merged